name: Build Rockbox
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make Rockbox tools directory
        run: mkdir -p "$HOME/rbtools/"

      - name: Install OS dependencies
        run: sudo apt-get install -y automake bison build-essential ccache flex libc6-dev libgmp3-dev libmpfr-dev libsdl1.2-dev libtool-bin texinfo zip gawk wget libmpc-dev gettext

      - name: Cache tools build
        id: cache-tools-build
        uses: actions/cache@v3
        with:
          path: ~/rbtools
          key: ${{ runner.os }}-rbtools-${{ hashFiles('tools/rockboxdev.sh') }}

      - name: Run Rockbox tools script
        if: steps.cache-tools-build.outputs.cache-hit != 'true'
        run: |
          cd tools
          chmod +x rockboxdev.sh
          RBDEV_TARGET="a" RBDEV_PREFIX="$HOME/rbtools/" ./rockboxdev.sh

      - name: Make Rockbox build directory
        run: mkdir build

      - name: Run configure
        run: |
          cd build
          PATH="$HOME/rbtools/bin":"$PATH" ../tools/configure --target=56 --type=n

      - name: Run make
        run: |
          cd build
          make -j

      - name: Run make zip
        run: |
          cd build
          make zip

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build
          ls -hla
          gh release create --draft test-release rockbox.zip
